"""Baseline schema

Revision ID: 98a52fe0c6a9
Revises: 
Create Date: 2025-11-05 16:20:14.412080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98a52fe0c6a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_transaction_logs_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_lead_admins_lead_admin_id'), table_name='lead_admins')
    op.drop_table('lead_admins')
    op.drop_index(op.f('ix_client_servers_server_id'), table_name='client_servers')
    op.drop_table('client_servers')
    op.drop_index(op.f('ix_client_api_keys_api_key_id'), table_name='client_api_keys')
    op.drop_table('client_api_keys')
    op.drop_table('ai_credit_ledger')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_workflows_workflow_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_ai_credit_entries_credit_entry_id'), table_name='ai_credit_entries')
    op.drop_table('ai_credit_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credit_entries',
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('credit_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('ai_credit_entries_client_id_fkey')),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], name=op.f('ai_credit_entries_execution_id_fkey'))
    )
    op.create_index(op.f('ix_ai_credit_entries_credit_entry_id'), 'ai_credit_entries', ['credit_entry_id'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.INTEGER(), server_default=sa.text("nextval('workflows_workflow_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workflow_id', name='workflows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_workflows_workflow_id'), 'workflows', ['workflow_id'], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.INTEGER(), server_default=sa.text("nextval('clients_client_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('client_id', name='clients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_table('ai_credit_ledger',
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('ai_credit_ledger_client_id_fkey')),
    sa.PrimaryKeyConstraint('client_id', name=op.f('ai_credit_ledger_pkey'))
    )
    op.create_table('client_api_keys',
    sa.Column('api_key_id', sa.INTEGER(), server_default=sa.text("nextval('client_api_keys_api_key_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('access_controls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='client_api_keys_client_id_fkey'),
    sa.PrimaryKeyConstraint('api_key_id', name='client_api_keys_pkey'),
    sa.UniqueConstraint('api_key', name='client_api_keys_api_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_client_api_keys_api_key_id'), 'client_api_keys', ['api_key_id'], unique=False)
    op.create_table('client_servers',
    sa.Column('server_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('server_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('server_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('server_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('client_servers_client_id_fkey')),
    sa.PrimaryKeyConstraint('server_id', name=op.f('client_servers_pkey'))
    )
    op.create_index(op.f('ix_client_servers_server_id'), 'client_servers', ['server_id'], unique=False)
    op.create_table('lead_admins',
    sa.Column('lead_admin_id', sa.INTEGER(), server_default=sa.text("nextval('lead_admins_lead_admin_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='lead_admins_client_id_fkey'),
    sa.PrimaryKeyConstraint('lead_admin_id', name='lead_admins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_lead_admins_lead_admin_id'), 'lead_admins', ['lead_admin_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('execution_id', sa.INTEGER(), server_default=sa.text("nextval('workflow_executions_execution_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lead_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['client_api_keys.api_key_id'], name='workflow_executions_api_key_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='workflow_executions_client_id_fkey'),
    sa.ForeignKeyConstraint(['lead_admin_id'], ['lead_admins.lead_admin_id'], name='workflow_executions_lead_admin_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name='workflow_executions_workflow_id_fkey'),
    sa.PrimaryKeyConstraint('execution_id', name='workflow_executions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_logs_pkey'))
    )
    op.create_index(op.f('ix_transaction_logs_id'), 'transaction_logs', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('feedback_client_id_fkey')),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.execution_id'], name=op.f('feedback_execution_id_fkey')),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('ix_feedback_feedback_id'), 'feedback', ['feedback_id'], unique=False)
    # ### end Alembic commands ###
